---
abstract: 'Validating payloads from GitHub'
author:
  - 'Songmu <y.songmu@gmail.com>'
build_requires:
  HTTP::Request::Common: '0'
  Plack::Test: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-HubSignature
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::Middleware::HubSignature:
    file: lib/Plack/Middleware/HubSignature.pm
    version: '0.01'
requires:
  Digest::SHA: '0'
  Plack::Middleware: '0'
  Plack::Request: '0'
  Plack::Util: '0'
  Plack::Util::Accessor: '0'
  String::Compare::ConstantTime: '0'
  parent: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/Songmu/p5-Plack-Middleware-HubSignature/issues
  homepage: https://github.com/Songmu/p5-Plack-Middleware-HubSignature
  repository: git://github.com/Songmu/p5-Plack-Middleware-HubSignature.git
version: '0.01'
x_authority: cpan:SONGMU
